#before batch
kraken2_db_to_RAM: |
  cp -r /home/data/REFERENCE_FILES/kraken2/human/ /dev/shm/
  cp -r /home/data/REFERENCE_FILES/kraken2/fungi/ /dev/shm/
  cp -r /home/data/REFERENCE_FILES/kraken2/16S_rdp/ /dev/shm/
kraken2_db_to_RAM_myco: |
  cp -r /home/data/REFERENCE_FILES/kraken2/16S_rdp/ /dev/shm/
  cp -r /home/data/REFERENCE_FILES/kraken2/mycobacteriaceae_tmp/ /dev/shm/
start_docker_ntm: >-
  f'docker run --privileged -d --name ntm_container -v {args["ref_dir"]}:/ref -v {folders["input_dir"]}:/input -v {folders["output_dir"]}:/output -v {folders["tmp_dir"]}:/tmp/ ntm_assembler_aligner sleep infinity'
create_chmod_loop_quast: >-
  docker exec ntm_container /bin/bash -c 'bash quast_unlocker.sh &'
#batch
#qc
kraken2_16S: >-
  f"{programms['kraken2']} --db /dev/shm/16S_rdp --threads {args['threads']} --paired {filenames['pair_of_fqs']} --report {filenames['kraken2_report_16S']} --output - --report-minimizer-data"
kraken2_fungi: >-
  f'{programms["kraken2"]} --db /dev/shm/fungi --threads {args["threads"]} --paired {filenames["pair_of_fqs"]} --report {filenames["kraken2_report_fungi"]} --output - --report-minimizer-data'
kraken2_human: >-
  f'{programms["kraken2"]} --db /dev/shm/human --threads {args["threads"]} --paired {filenames["pair_of_fqs"]} --report {filenames["kraken2_report_human"]} --output - --report-minimizer-data'
fastqc: >-
  f'{programms["fastqc"]} --quiet --threads 2 -o {folders["fastqc_dir"]} {filenames["pair_of_fqs"]}'
kraken2_myco_16S: >-
  f"{programms['kraken2']} --db /dev/shm/16S_rdp --threads {args['threads']} --paired {filenames['pair_of_fqs']} --minimum-hit-groups 1 --output - --classified-out {filenames['kraken2_out_fq']}"
kraken2_myco: >-
  f'{programms["kraken2"]} --db /dev/shm/mycobacteriaceae_tmp --threads {args["threads"]} --paired {filenames["kraken2_out_fq"].replace("#","*")} --report {filenames["kraken2_report_myco"]} --output - --report-minimizer-data'


#de_novo_assembling_docker
spades: >-
  f"spades.py -o {folders['tmp_dir']} -1 {filenames["pair_of_fqs"][0]} -2 {filenames["pair_of_fqs"][1]}
  -t {args["threads"]} --careful -m 100 -k 21,33,55,77 --phred-offset 33"
#4min per 1M reads (72 cores)
spades_docker:
  - 600
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms["spades"]} -o /tmp --isolate
    -1 /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][0]} -2 /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][1]}
    --threads {args["threads"]} -m 100 -k 21,33,55,77'"""
spades_docker_no_isolate:
  - 600
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms["spades"]} -o /tmp
    -1 /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][0]} -2 /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][1]}
    --threads {args["threads"]} -m 100 -k 21,33,55,77'"""
spades_docker_only_assembler_unpaired_r2_only:
  - 600
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms["spades"]} -o /tmp --only-assembler
    -s /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][1]}
    --threads {args["threads"]} -m 100 -k 21,33,55,77'"""
spades_docker_meta:
  - 600
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms["spades"]} -o /tmp --meta
    -1 /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][0]} -2 /input/{filenames["run_id"]}/{filenames["pair_of_fqs"][1]}
    --threads {args["threads"]} -m 100 -k 21,33,55,77'"""
polishing_bwa_docker: >-
  f"""docker exec ntm_container /bin/bash -c '{programms["bwa_mem2"]} index /tmp/contigs.fasta
  && {programms["bwa_mem2"]} mem -t {args["threads"]} -M /tmp/contigs.fasta /input/{filenames["run_id"]}/{filenames["basename"]}*.fq.gz
  | samtools view -@ {args["threads"]} -S -b -F 4 -F 8 -F 256 > /tmp/0.bam
  && time samtools sort -@ {args["threads"]} /tmp/0.bam > /tmp/frags.bam
  && samtools index -@ {args["threads"]} /tmp/frags.bam'"""
polishing_pilon_docker: >-
  f"""docker exec ntm_container /bin/bash -c '{programms["pilon"]} --genome /tmp/contigs.fasta
  --frags /tmp/frags.bam --output {filenames["basename"]} --outdir /output/{os.path.basename(os.path.normpath(folders["fasta_dir"]))}'"""
polishing_pilon_docker_r2_only: >-
  f"""docker exec ntm_container /bin/bash -c '{programms["pilon"]} --genome /tmp/contigs.fasta
  --frags /tmp/frags.bam --output {filenames["basename"]}_r2 --outdir /output/{os.path.basename(os.path.normpath(folders["fasta_dir"]))}'"""
FIX_polishing_abacas_docker: >-
  'perl /home/data/Programms/abacas/abacas.1.3.1.pl -r {} -q {} -p nucmer -i 20 -c -o {}{}_abacas'
#qc_assembling_docker
busco_docker: >-
  f"""docker exec ntm_container /bin/bash -c '{programms['busco']} -i /input/fasta/{f"{filenames['filename']}.fasta"} --cpu {args['threads']}
  --out_path /tmp/ --mode genome --lineage /ref/bacteria_odb10/ --offline --out busco --force'"""
quast_docker_0:
  - 30
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms['quast']} --threads {args['threads']} -o /tmp/ -r /ref/bwa/*{args['refs4ids'][filenames["basename"]][0]}*.fna
    /input/fasta/{f"{filenames['filename']}.fasta"}
    -1 /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][0]} -2 /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
    --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats'"""
quast_chown_0: >-
  f"""docker exec ntm_container /bin/bash -c 'chmod -R 777 /tmp/'"""
quast_docker_1: >-
    f"""docker exec ntm_container /bin/bash -c '{programms['quast']} --threads {args['threads']} -o /tmp/ -r /ref/bwa/*{args['refs4ids'][filenames["basename"]][0]}*.fna
    /input/fasta/{f"{filenames['filename']}.fasta"}
    -1 /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][0]} -2 /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
    --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats && chmod -R 777 /tmp/'"""
quast_chown_1: >-
  f"""docker exec ntm_container /bin/bash -c 'chmod -R 777 /tmp/'"""
quast_docker_2: >-
  f"""docker exec ntm_container /bin/bash -c '{programms['quast']} --threads {args['threads']} -o /tmp/ -r /ref/bwa/*{args['refs4ids'][filenames["basename"]][0]}*.fna
  /input/fasta/{f"{filenames['filename']}.fasta"}
  -1 /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][0]} -2 /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
  --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats && chmod -R 777 /tmp/'"""
parse_busco: >-
  f'python3 {args["project_path"]}/src/busco_parser.py {filenames["basename"]} {filenames["busco"]} {folders['output_dir']}busco.xlsx'
parse_quast: >-
  f'python3 {args["project_path"]}/src/quast_parser.py {filenames["basename"]} {args["species4ids"][filenames["basename"]]} {filenames['quast_report']} {folders['output_dir']}quast.xlsx'
rm_tmp_files_docker: >-
  f"""docker exec ntm_container /bin/bash -c 'mv /tmp/* /ref/'"""
quast: >-
    f"""{programms['quast']} --threads {args['threads']} -o {folders['tmp_dir']} -r {args['ref_dir']}*{args['refs4ids'][filenames["basename"]][0]}*.fna
    {folders['input_dir']}fasta/{f"{filenames['filename']}.fasta
    -1 {folders['input_dir']}fq/{filenames['run_id']}/{filenames['pair_of_fqs'][0]} -2 {folders['input_dir']}fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
    --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats'"""

# r2 only
quast_docker_0_r2_only:
  - 30
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms['quast']} --threads {args['threads']} -o /quast/ -r /ref/bwa/*{args['refs4ids'][filenames["basename"]][0]}*.fna
    /input/fasta/{f"{filenames['filename']}.fasta"}
    --single /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
    --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats && cp -r /quast/ /tmp/ && chmod -R 777 /tmp/quast/'"""
quast_docker_1_r2_only:
  - 90
  - >-
    f"""docker exec ntm_container /bin/bash -c '{programms['quast']} --threads {args['threads']} -o /quast/ -r /ref/bwa/*{args['refs4ids'][filenames["basename"]][0]}*.fna
    /input/fasta/{f"{filenames['filename']}.fasta"}
    --single /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
    --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats'"""
quast_docker_2_r2_only: >-
  f"""docker exec ntm_container /bin/bash -c '{programms['quast']} --threads {args['threads']} -o /quast/ -r /ref/bwa/*{args['refs4ids'][filenames["basename"]][0]}*.fna
  /input/fasta/{f"{filenames['filename']}.fasta"}
  --single /input/fq/{filenames['run_id']}/{filenames['pair_of_fqs'][1]}
  --min-contig 500 --use-all-alignments --k-mer-stats --no-plots --no-read-stats && cp -r /quast/ /tmp/ && chmod -R 777 /tmp/quast/'"""
#vcf_calling

#same, no docker
mkdir_tmp: >-
  f"""mkdir {folders["tmp_dir"]}"""
bwa: >-
  f"""{programms['meme']} -t {args["threads"]} -M -R "@RG\\tID:{filenames["basename"]}\\tLB:{filenames["run_id"]}\\tPL:MGI\\tPM:G50\\tSM:{filenames["basename"]}"
  {args["ref_dir"]}*{args["refs4ids"][filenames["basename"]][0]}*.fna {folders["input_dir"]}{filenames["run_id"]}/{filenames["pair_of_fqs"][0]} {folders["input_dir"]}{filenames["run_id"]}/{filenames["pair_of_fqs"][1]}
  > {folders["tmp_dir"]}0.sam"""
gatk_sort_sam: >-
  f"""{programms['gatk']} SortSamSpark --spark-master local[{args["threads"]}] -I {folders["tmp_dir"]}0.sam
  -O {folders["tmp_dir"]}0_sorted.bam -SO coordinate"""
gatk_mark_duplicates: >-
  f"""{programms['gatk']} MarkDuplicatesSpark --spark-master local[{args["threads"]}] -I {folders["tmp_dir"]}0_sorted.bam
  -O {folders["bam_dir"]}{filenames["basename"]}.bam --metrics-file {folders["tmp_dir"]}0_metrics.txt"""
gatk_build_bam_index: >-
  f"""{programms['gatk']} BuildBamIndex -I {folders["bam_dir"]}{filenames["basename"]}.bam"""
gatk_base_recalibrator: >-
  f"""{programms['gatk']} BaseRecalibratorSpark --spark-master local[{args["threads"]}] --interval-padding 50
  -R {args["ref_dir"]}*{args["refs4ids"][filenames["basename"]][0]}*.fna
  -RF GoodCigarReadFilter -I {folders["tmp_dir"]}sorted_dedup.bam -O {folders["tmp_dir"]}sorted_dedup_reads.bam_recal_data.table"""
gatk_print_reads: >-
  f"""{programms['gatk']} PrintReadsSpark --spark-master local[{args["threads"]}] -R {args["ref_dir"]}*{args["refs4ids"][filenames["basename"]][0]}*.fna -rf BadCigar
  -BQSR {folders["tmp_dir"]}sorted_dedup_reads.bam_recal_data.table -I {folders["tmp_dir"]}sorted_dedup_reads.bam
  -O {folders["bam_dir"]}{filenames["basename"]}.bam --allow_potentially_misencoded_quality_scores"""
gatk_haplotype_caller: >-
  f"""{programms['gatk']} HaplotypeCallerSpark --spark-master local[{args["threads"]}]
  -R {args["ref_dir"]}*{args["refs4ids"][filenames["basename"]][0]}*.fna --interval-padding 50 -I {folders["bam_dir"]}{filenames["basename"]}.bam 
  -ploidy 1 -O {folders["vcf_dir"]}{filenames["basename"]}_ploidy.vcf"""
rm_tmp_files: >-
  f"""rm -rf {folders["tmp_dir"]}*"""
rm_tmp_dir: >-
  f"""rm -rf {folders["tmp_dir"]}"""


#after batch
kraken2_out_of_RAM_myco: |
  rm -rf /dev/shm/16S_rdp/
  rm -rf /dev/shm/mycobacteriaceae_tmp/
kraken2_out_of_RAM: |
  rm -rf /dev/shm/16S_rdp/
  rm -rf /dev/shm/human/
  rm -rf /dev/shm/fungi/
multiqc:
  f'{programms["multiqc"]} {folders["output_dir"]} --outdir {folders["multiqc_dir"]} --interactive --export --quiet'
stop_docker_ntm: |
  docker container stop ntm_container
  docker container rm ntm_container