dell:
  envs:
    gatk: gatk
  binaries:
    kraken2: kraken2
    fastqc: fastqc
    gatk: gatk
    multiqc: multiqc
    picard: java -jar picard.jar
    quast: /home/data/Programms/quast-5.2.0/quast.py
    meme: /home/data/Programms/BWA-MEME/bwa-meme mem
  env_command: conda run -n env binary

z8:
  envs:
    busco: "busco"
  binaries:
    busco: "busco"
    pilon: "java -Xmx24G -jar /programms/pilon-1.24.jar"
    bwa_mem2: "/programms/bwa-mem2-2.2.1_x64-linux/bwa-mem2"
    spades: "cd /programms/SPAdes-4.0.0-Linux/bin/ && ./spades.py"
    quast: "/root/miniconda3/bin/quast.py"
  env_command: "/root/miniconda3/bin/conda run -n env binary"