n_farcinica_Mycobacterium_tuberculosis: Mycobacterium_tuberculosis
n_farcinica_Mycobacterium_attenuatum: Mycobacterium_attenuatum
n_farcinica_Mycobacterium_avium: Mycobacterium_avium
n_farcinica_Mycobacterium_celatum: Mycobacterium_celatum
n_farcinica_Mycobacterium_gordonae: Mycobacterium_gordonae
n_farcinica_Mycobacterium_intracellulare: Mycobacterium_intracellulare
n_farcinica_Mycobacterium_kansasii: Mycobacterium_kansasii
n_farcinica_Mycobacterium_lentiflavum: Mycobacterium_lentiflavum
n_farcinica_Mycobacterium_malmoense: Mycobacterium_malmoense
n_farcinica_Mycobacterium_marseillense: Mycobacterium_marseillense
n_farcinica_Mycobacterium_palustre: Mycobacterium_palustre
n_farcinica_Mycobacterium_paraffinicum: Mycobacterium_paraffinicum
n_farcinica_Mycobacterium_paragordonae: Mycobacterium_paragordonae
n_farcinica_Mycobacterium_paraintracellulare: Mycobacterium_paraintracellulare
n_farcinica_Mycobacterium_persicum: Mycobacterium_persicum
n_farcinica_Mycobacterium_pseudokansasii: Mycobacterium_pseudokansasii
n_farcinica_Mycobacterium_timonense: Mycobacterium_timonense
n_farcinica_Mycobacterium_xenopi: Mycobacterium_xenopi
n_farcinica_Mycobacteroides_abscessus: Mycobacteroides_abscessus
n_farcinica_Mycobacteroides_chelonae: Mycobacteroides_chelonae
n_farcinica_Mycolicibacter_kumamotonensis: Mycolicibacter_kumamotonensis
n_farcinica_Mycolicibacterium_aichiense: Mycolicibacterium_aichiense
n_farcinica_Mycolicibacterium_conceptionense: Mycolicibacterium_conceptionense
n_farcinica_Mycolicibacterium_fortuitum: Mycolicibacterium_fortuitum
n_farcinica_Mycolicibacterium_holsaticum: Mycolicibacterium_holsaticum
n_farcinica_Mycolicibacterium_mageritense: Mycolicibacterium_mageritense
n_farcinica_Mycolicibacterium_mucogenicum: Mycolicibacterium_mucogenicum
n_farcinica_Mycolicibacterium_novocastrense: Mycolicibacterium_novocastrense
n_farcinica_Mycolicibacterium_psychrotolerans: Mycolicibacterium_psychrotolerans
n_farcinica_Mycolicibacterium_septicum: Mycolicibacterium_septicum
n_farcinica_Mycolicibacterium_wolinskyi: Mycolicibacterium_wolinskyi
