Mycobacterium_tuberculosis: Mycobacterium_tuberculosis
Mycobacterium_attenuatum: Mycobacterium_attenuatum
Mycobacterium_avium: Mycobacterium_avium
Mycobacterium_celatum: Mycobacterium_celatum
Mycobacterium_gordonae: Mycobacterium_gordonae
Mycobacterium_intracellulare: Mycobacterium_intracellulare
Mycobacterium_kansasii: Mycobacterium_kansasii
Mycobacterium_lentiflavum: Mycobacterium_lentiflavum
Mycobacterium_malmoense: Mycobacterium_malmoense
Mycobacterium_marseillense: Mycobacterium_marseillense
Mycobacterium_palustre: Mycobacterium_palustre
Mycobacterium_paraffinicum: Mycobacterium_paraffinicum
Mycobacterium_paragordonae: Mycobacterium_paragordonae
Mycobacterium_paraintracellulare: Mycobacterium_paraintracellulare
Mycobacterium_persicum: Mycobacterium_persicum
Mycobacterium_pseudokansasii: Mycobacterium_pseudokansasii
Mycobacterium_timonense: Mycobacterium_timonense
Mycobacterium_xenopi: Mycobacterium_xenopi
Mycobacteroides_abscessus: Mycobacteroides_abscessus
Mycobacteroides_chelonae: Mycobacteroides_chelonae
Mycolicibacter_kumamotonensis: Mycolicibacter_kumamotonensis
Mycolicibacterium_aichiense: Mycolicibacterium_aichiense
Mycolicibacterium_conceptionense: Mycolicibacterium_conceptionense
Mycolicibacterium_fortuitum: Mycolicibacterium_fortuitum
Mycolicibacterium_holsaticum: Mycolicibacterium_holsaticum
Mycolicibacterium_mageritense: Mycolicibacterium_mageritense
Mycolicibacterium_mucogenicum: Mycolicibacterium_mucogenicum
Mycolicibacterium_novocastrense: Mycolicibacterium_novocastrense
Mycolicibacterium_psychrotolerans: Mycolicibacterium_psychrotolerans
Mycolicibacterium_septicum: Mycolicibacterium_septicum
Mycolicibacterium_wolinskyi: Mycolicibacterium_wolinskyi
