Mycobacterium_avium: >-
  GCA_022175585.1_ASM2217558v1
Mycobacterium_intracellulare: >-
  GCA_020736005.1_ASM2073600v1
Mycobacterium_kansasii: >-
  GCA_000157895.2_ASM15789v2
Mycolicibacterium_fortuitum: >-
  GCA_027570695.1_ASM2757069v1
Mycobacterium_gordonae: >-
  GCA_002101675.1_ASM210167v1
Mycobacterium_xenopi: >-
  GCA_900453395.1_53750_B01
Mycobacterium_lentiflavum: >-
  GCA_001373395.1_PRJEB8430_assembly_1
Mycobacteroides_abscessus: >-
  GCA_004028015.1_ASM402801v1
Mycolicibacterium_wolinskyi: >-
  
Mycolicibacterium_novocastrense: >-
  
Mycolicibacterium_aichiense: >-
  
Mycobacterium_paraffinicum: >-
  
Mycolicibacterium_holsaticum: >-
  
Mycobacterium_celatum: >-
  
Mycolicibacterium_septicum: >-
  
Mycolicibacter_kumamotonensis: >-
  
Mycobacterium_palustre: >-
  
Mycobacterium_marseillense: >-
  
Mycolicibacterium_psychrotolerans: >-
  
Mycolicibacterium_mucogenicum: >-
  
Mycobacterium_pseudokansasii: >-
  
Mycolicibacterium_mageritense: >-
  
Mycobacterium_paraintracellulare: >-
  
Mycobacterium_sp.: >-
  
Mycobacterium_timonense: >-
  
Mycobacterium_paragordonae: >-
  
Mycobacterium_malmoense: >-
  
Mycobacterium_attenuatum: >-
  
Mycolicibacterium_conceptionense: >-
  
Mycobacterium_persicum: >-
  
Mycobacteroides_chelonae: >-