Mycobacterium_attenuatum: LAUMK41
Mycobacterium_avium: ASM2217558v1
Mycobacterium_celatum: ASM210159v1
Mycobacterium_gordonae: ASM210167v1
Mycobacterium_intracellulare: ASM2073600v1
Mycobacterium_kansasii: ASM15789v2
Mycobacterium_lentiflavum: GCA_001373395.1_PRJEB8430_assembly_1
Mycobacterium_malmoense: ASM1964585v1
Mycobacterium_marseillense: ASM228571v1
Mycobacterium_palustre: ASM210178v1
Mycobacterium_paraffinicum: ASM2582286v1
Mycobacterium_paragordonae: 	ASM361443v1
Mycobacterium_paraintracellulare: ASM27682v1
Mycobacterium_persicum: ASM208691v1
Mycobacterium_pseudokansasii: MK142
Mycobacterium_timonense: ASM2582198v1
Mycobacterium_xenopi: GCA_900453395.1_53750_B01
Mycobacteroides_abscessus: ASM402801v1
Mycobacteroides_chelonae: ASM163280v1
Mycolicibacter_kumamotonensis: ASM208628v1
Mycolicibacterium_aichiense: ASM1072624v1
Mycolicibacterium_conceptionense: ASM210206v1
Mycolicibacterium_fortuitum: ASM2757069v1
Mycolicibacterium_holsaticum: ASM1964583v1
Mycolicibacterium_mageritense: ASM1072747v1
Mycolicibacterium_mucogenicum: ASM567068v2
Mycolicibacterium_novocastrense: ASM149983v1
Mycolicibacterium_psychrotolerans: ASM1072930v1
Mycolicibacterium_septicum: ASM1691934v1
Mycolicibacterium_wolinskyi: ASM210196v1
